genome: 
specie_name: 

# protein evidence
protein: 

# RNA-seq evidence
transcript_assemble: True
sample: "samples.csv"
transcript_gtf:
transcript_fasta:

# modeling training
training_model: True
training_snap_round: 0
training_augustus_round: 1
training_augustus_opt_round: 1
training_augustus_gene_num: 1000
training_augustus_opts: ""

# if training_model is False, existed model must be set
##path to snap hmm file
snaphmm:
## "augustus species name
augustus_species:

# MAKER setting
parallel: True

## MAKER setting of annotation
prediciton:
  opts:
    - model_org=
    - rmlib=TElib.fa
    - min_protein=10
    - always_complete=0

## MAKER settings of training
round1:
  bopts:
    - pcov_blastn=0.9
    - depth_blastn=2
    - pcov_blastx=0.6
    - pid_blastx=0.5
    - depth_blastx=2
  opts:
    - model_org=
    - rmlib=TElib.fa
    - min_protein=100
    - always_complete=0

# minimap2 paramater
mm2_idx_opts: ""
mm2_idx_threads: 10
mm2_map_threads: 20
mm2_pb_map_opts: ""
mm2_ont_map_opts: ""
mm2_pb_min_mq: 40
mm2_ont_min_mq: 40


# STAR aligner parameter
star_idx_opts: "--genomeSAindexNbases 12"
star_idx_threads: 10

# StringTie paramter
stringtie_thread: 10
ngs_stringtie_assembly_opts: ""
ngs_rf_stringtie_assembly_opts: ""
ngs_fr_stringtie_assembly_opts: ""
tgs_pb_stringtie_assembly_opts: ""
tgs_ont_stringtie_assembly_opts: ""