# reference fasta path
genome:
specie_name:

# protein evidence
protein:

# RNA-seq evidence
transcript_assemble: True
sample: "samples.csv"
gtf:
transcript_fasta:

# modeling training
training_model: True
training_snap_round: 123
training_augustus_round: 3

# if training_model is False, existed model must be set
##path to snap hmm file
snaphmm: 
## "augustus species name
augustus_species: 

# MAKER setting
parallel: True

## MAKER setting of annotation
prediciton:
  opts:
    - model_org=arabidopsis
    - min_protein=100
    - always_complete=1

## MAKER settings of training
round1:
  bopts:
    - pcov_blastn=0.9
    - depth_blastn=2
    - pcov_blastx=0.6
    - pid_blastx=0.5
    - depth_blastx=2
  opts:
    - model_org=arabidopsis
    - min_protein=100
    - always_complete=0

round2:
  bopts:
    - pcov_blastn=0.9
    - depth_blastn=2
    - pcov_blastx=0.6
    - pid_blastx=0.5
    - depth_blastx=2
  opts:
    - model_org=arabidopsis

round3:
  bopts:
    - pcov_blastn=0.9
    - depth_blastn=2
    - pcov_blastx=0.6
    - pid_blastx=0.5
    - depth_blastx=2
  opts:
    - model_org=arabidopsis